### ISSUE TITLE
Wrong way to import image

### ISSUE THREAD

**Issue by Kaziaminulislamrahat** [Lukas0025/python-pixabay#1]
I have tried import image but i couldn't do it. always show this message.
**ImportError: cannot import name 'Image' from 'pixabay' (/usr/local/lib/python3.7/dist-packages/pixabay/__init__.py)**

how can i solve this 
![pixabay issue](https://user-images.githubusercontent.com/48948533/166225650-3eb80998-d7a9-4f2f-9a81-2abc3710106c.jpg)

**Comment by Lukas0025** [comment]
Do not import image from pixabay this way. For this code you dont need image module.  Make sure if you using https://pypi.org/project/pixabay/

This exmaple show how to use SDK for get all images with "notebook" query.
```python
import pixabay.core

# init pixabay API
px = pixabay.core("YOUR API KEY")

# search for notebook, category: computers, color: black, minWidth 100px with safeSearch (more in https://pixabay.com/api/docs/)
notebooks = px.query(
    query      = "notebook",
    category   = "computers",
    colors     = "black",
    minWidth   = "100",
    safeSearch = True
)

# get len of hits len(notebooks)
print("{} hits".format(len(notebooks)))

# get image id
print(notebooks[0].getId()) 
```

Notebooks is array with `image` objects and you can use methods on this object to get data more you can find in documentation https://python-pixabay.readthedocs.io/en/latest/classpixabay_1_1image_1_1image.html

If you realy want import image module you can do it as `import pixabay.image.image as image`
