### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by AvetyNS** [Lukas0025/python-pixabay#6]
After using:

pip install pixabay

And running the script I got:

import pixabay.core
ModuleNotFoundError: No module named 'pixabay'

**Comment by Lukas0025** [comment]
is pip alias for pip3. Are you running python3? Please add more information (your script, your architecture, exact steps to replicate error, etc).

**Comment by AvetyNS** [comment]
I am using Win 10 machine, pip is alias for pip3 , I am using python3. When I was trying to run the script (copied from this repo) with python's default IDE I was unable to run and received the error mentioned above. However , when I tried to run it simply by double clicking on the script it was running for a while downloaded few videos then it crashed.

**Comment by AvetyNS** [comment]
Solved , issue was on my side since I downloaded the package to python 3.11 , but was using IDE 3.10

**Comment by giggioman00** [comment]
I have this same problem for the same example code... wxcept that I'm not running multiple versions of Python on my system. I correctly see the module in the installation folders. So it is downloaded correctly. But it gives me that error on line 1
